version: '3.7'

services:
  simple-node:
    command: yarn start
    build:
      context: .
    image: espatola/docker-simple-node
    container_name: simple-node
    ports:
      - 80:80
    healthcheck:
      test: curl --fail --max-time 1 http://localhost/
      start_period: 5s
      interval: 20s
      retries: 3